### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by cyb3rsalih** [opengineer/intelligo#18]
**Is your feature request related to a problem? Please describe.**
Yes I can't try the framework with run an example project.

**Describe the solution you'd like**
I expect `npm start` or `npm run` will open a web page of the project.

**Describe alternatives you've considered**
firstly I installed node packages with `npm install` after that
I tried `npm start` and `npm run` commands. Get this output:
```
Lifecycle scripts included in intelligo:
  postinstall
    opencollective-postinstall
  test
    mocha --recursive test/*

available via `npm run-script`:
  test:watch
    npm test -- --watch
```

- `npm run-script` gives same output
- Googled the output for any solution also
- Also look for any readme or build file.

**Comment by doljko** [comment]
Here is some example.
https://github.com/opengineer/jisho-bot/blob/master/index.js

**Comment by cyb3rsalih** [comment]
Thank you! with `node index.js ` I can run the project. Now error message says 
I need these 3 values. 
```
    "APP_SECRET": "",
    "PAGE_ACCESS_TOKEN": "",
    "VALIDATION_TOKEN": ""
```
From `developers.facebook.com` when I create my app I can see the `app_secret` .
But  can't  see  2 others. Could you help me for this?
